name: Cluster tests (OpenJDK11 & MySQL)

on: [push, pull_request]

jobs:
  ubuntu:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Set up MySQL
        run: |
            sudo /etc/init.d/mysql start
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build in JDK 11
        run: mvn -B clean install -DskipTests --file pom.xml
      - name: Cluster Tests
        run: mvn -B clean install --file integration/pom.xml -P cluster-tests
