name: Integration tests (Windows, OpenJDK8)

on: [push]

jobs:
  tests-mediators1_2_other_sample:

    runs-on: windows-latest

    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean install -P tests-mediators1_2_other_sample --file pom.xml -fae

  tests-service_patches_servicesamples_dss:

    runs-on: windows-latest

    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean install -P tests-service_patches_servicesamples_dss --file pom.xml -fae

  tests-transport:

    runs-on: windows-latest

    steps:
      - name: Support longpaths
        run: git config --system core.longpaths true
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: joschi/setup-jdk@v2
        with:
          distribution: 'adopt'
          java-version: 11
      - name: Build with Maven
        run: mvn -B clean install -P tests-transport --file pom.xml -fae

